### ISSUE TITLE
DSG for Dutch

### ISSUE THREAD

**Issue by eriktks** [navigating-stories/notebooks#8]
## Create a working demo for Digital Stiory Grammar for Dutch.

Reference: Stefan Bastholm Andrade & Ditte Andersen (2020) Digital story grammar: a quantitative methodology for narrative analysis, International Journal of Social Research Methodology, 23:4, 405-421, DOI: 10.1080/13645579.2020.1723205 [abstract](https://doi.org/10.1080/13645579.2020.1723205)

For this task we created the Jupyter notebook [stroll_srl_test.ipynb](https://github.com/navigating-stories/notebooks/blob/main/stroll_srl_test.ipynb)

### Tasks

* [x] find dependency parser for Dutch: we chose [stanza](https://stanfordnlp.github.io/stanza/)
* [x] find a semantic role labeler for Dutch: we chose [stroll](https://github.com/Filter-Bubble/stroll/)
* [x] convert dependency parsing output to table
* [x] convert semantic role labeler output to table
* [x]  aggregate the table outputs to answer the narrative questions who, where, when, what, why and how
* [x] use verb classes to model narrative topics
* [x] collect ideas on how to proceed after this
