### ISSUE TITLE
DSG for Danish

### ISSUE THREAD

**Issue by eriktks** [navigating-stories/notebooks#9]
## Create a working demo for Digital Stiory Grammar for Danish.

Reference: Stefan Bastholm Andrade & Ditte Andersen (2020) Digital story grammar: a quantitative methodology for narrative analysis, International Journal of Social Research Methodology, 23:4, 405-421, DOI: 10.1080/13645579.2020.1723205 [abstract](https://doi.org/10.1080/13645579.2020.1723205)

For this task we created the Jupyter notebook [dannlp_test.ipynb](https://github.com/navigating-stories/notebooks/blob/main/dannlp_test.ipynb)

### Tasks

* [x] find dependency parser for Danish: we chose [DaNLP](https://pypi.org/project/danlp/)
* [ ] find a semantic role labeler for Danish: we did not find a usable semantic role labeler for Danish
* [x] convert dependency parsing output to table
* [ ] convert semantic role labeler output to table
* [x]  aggregate the table outputs to answer the narrative questions who, where, when, what, why and how
* [ ] use verb classes to model narrative topics
* [ ] collect ideas on how to proceed after this
